### ISSUE TITLE
No module named 'text_processing'

### ISSUE THREAD

**Issue by summitgao** [tbmoon/basic_vqa#1]
when running:
python build_vqa_inputs.py --input_dir='../datasets' --output_dir='../datasets'

I encountered a problem:

Traceback (most recent call last):
  File "build_vqa_inputs.py", line 5, in <module>
    import text_processing
ModuleNotFoundError: No module named 'text_processing'

**Comment by Axe--** [comment]
Hey, replace as follows: 
~~`import text_processing`~~
`import text_helper`

**Comment by tbmoon** [comment]
Thanks! summitgao and Axe--!" I fixed this!
