### ISSUE TITLE
How to generate results?

### ISSUE THREAD

**Issue by AmoghTiwari** [tbmoon/basic_vqa#9]
Once I have trained the model, what are the steps which I need to follow in order to get the results?

**Comment by AmitSharma1127** [comment]
My training is painfully slow. Did you face a similar issue?

**Comment by AmoghTiwari** [comment]
> My training is painfully slow. Did you face a similar issue?

I used a batch size of 128 and trained for 45 epochs. It took me slightly less than 1 hour for each epoch and I was using a remore machine with a "moderate" GPU. So it was slow, but I think this much is expected when training heavy models on large datasets.

Have you resized the images though? Resizing makes a big difference. This repo has a script to resize the images.

**Comment by AmitSharma1127** [comment]
Thanks for sharing the details. Would you mind sharing which remote machine service did you use to train this? This can not be done  with the free colab version.

**Comment by AmoghTiwari** [comment]
I used a remote machine provided by my university. They have GeForce 1080Ti and RTX 2080. I am  not sure which one from among those two I had used.
Also, if you want to use colab what you can do is - (1) Save the model after each epoch; (2) When the colab run time gets disconnected and you start training again, start training from the previous saved epoch. (https://pytorch.org/tutorials/beginner/saving_loading_models.html <- This might help with saving and loading models)

**Comment by charani2000** [comment]
> Once I have trained the model, what are the steps which I need to follow in order to get the results?

Hello, are you able to get results?

**Comment by AmoghTiwari** [comment]
Yes. I had used the below code as a python script.

I took most of this by looking at the main.py, file

[my_prediction_script.txt](https://github.com/tbmoon/basic_vqa/files/8200209/my_prediction_script.txt)
